# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapboxCompassMapViewSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Mapbox-iOS-SDK-symbols', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.6.0/platform/ios/Mapbox-iOS-SDK-symbols.podspec'
  # Pods for MapboxCompassMapViewSwift

end
